import {
  type LightbulbIcon as LucideProps,
  Pill,
  AlertCircle,
  FileText,
  RefreshCw,
  FileCheck,
  BarChart3,
  Loader2,
  Shield,
  Lock,
  Key,
  UserCheck,
  Database,
  Link2,
  FileSpreadsheet,
  Mail,
  PenTool,
  FlaskRoundIcon as Flask,
  Globe,
} from "lucide-react"

export type IconProps = LucideProps

export const Icons = {
  logo: Pill,
  spinner: Loader2,
  alert: AlertCircle,
  submission: FileText,
  variation: RefreshCw,
  renewal: FileCheck,
  report: BarChart3,
  security: Shield,
  encryption: Lock,
  authentication: Key,
  authorization: UserCheck,
  database: Database,
  integration: Link2,
  erp: FileSpreadsheet,
  email: Mail,
  esignature: PenTool,
  lims: Flask,
  globe: Globe,
}
